# Generated by Django 4.2.4 on 2023-08-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=234234),
            preserve_default=False,
        ),
    ]
